###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: webserver
      working_dir: /application
      volumes:
          - ./:/application
          - ./docker/local/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8008:80"

    php-fpm:
      build: docker/local/phpdocker/php-fpm
      container_name: php-fpm
      working_dir: /application
      volumes:
        - ./:/application
        - ./docker/local/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

    mariadb:
      image: mariadb:10.4
      container_name: db-mariadb
      working_dir: /application
      volumes:
        - ./app:/application
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=database
        - MYSQL_USER=username
        - MYSQL_PASSWORD=password

    pma:
      depends_on:
        - mariadb
      image: phpmyadmin/phpmyadmin
      container_name: mariadb-phpmyadmin
      restart: always
      ports:
        - '8890:80'
      environment:
        PMA_HOST: mariadb

    storage:
      image: minio/minio
      container_name: minio-storage
      environment:
        MINIO_ACCESS_KEY: access_key
        MINIO_SECRET_KEY: secret_key
      volumes:
        - ./services/storage:/data
      command: server /data
      ports:
        - '7006:9000'